SSCS-9668
hmcts/sscs-tribunals-case-api pull request #2394
Opened 2021-10-20 16:23 UTC by gmikerlemos

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-9668

### Change description ###

Child Support - Upload response event - edited reason child support confidentiality

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-11-10 12:35 UTC, jackmaloney commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java
> +        return !sscsCaseData.isBenefitType(Benefit.CHILD_SUPPORT);
The method name of this one doesn't really make sense to me considering it's just checking if it is not a child support case. I've tried to get my head round this whole logic a few times and im pretty confused as to what is going on. Is there anyway to make clearer? Or if not, maybe put a comment as to what this is actually doing?

2021-11-10 13:33 UTC, jackmaloney commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
> +    public void givenADwpUploadResponseEventPmheNonChildSupportThenNoErrorAdded() {
typo in test name for phme

2021-11-10 13:39 UTC, jackmaloney requested changes

2021-11-10 13:39 UTC, jackmaloney commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandlerTest.java
> +        assertEquals(0, response.getErrors().size());
Is this actually a useful test? Shouldn't we check that the class actually hits the expected methods and gets the correct number of bundles when it is a Child Support case with edited docs?

2021-11-11 14:42 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java
> +        for (AudioVideoEvidence audioVideo : dwpAudioVideoEvidence) {
???

2021-11-11 15:56 UTC, jackmaloney approved these changes

2021-11-12 11:15 UTC, merged