sscs 9882 set caseName for SYA
hmcts/sscs-tribunals-case-api pull request #2487
Opened 2021-12-17 17:15 UTC by chrisdavecm

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-9882

### Change description ###
caseName field for SYA

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-12-20 11:14 UTC, ryandac approved these changes

2021-12-20 14:36 UTC, rasikasri requested changes

2021-12-20 14:36 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
> +            if (appeal.getAppellant() != null & appeal.getAppellant().getName() != null) {
bitwise & operator is invalid here. Would cause null pointer as well

2021-12-22 12:08 UTC, rasikasri approved these changes

2021-12-23 11:31 UTC, merged