Feat/sscs 10351
hmcts/sscs-tribunals-case-api pull request #2717
Opened 2022-05-26 12:27 UTC by HarryH96

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10351

### Change description ###
- Adding check on Action Further Evidence for `getSchedulingAndListingFields().getHearingRoute()` GAPS cases to throw an error

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-26 12:45 UTC, johnoneill46 approved these changes

2022-05-28 15:25 UTC, johnoneill46 requested changes

2022-05-28 15:25 UTC, johnoneill46 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/validsendtointerloc/ValidSendToInterlocMidEventHandler.java
> +        if (HearingRoute.GAPS.equals(sscsCaseData.getRegionalProcessingCenter().getHearingRoute())
Tests required?

2022-05-28 15:25 UTC, johnoneill46 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
> +        if (HearingRoute.GAPS.equals(sscsCaseData.getRegionalProcessingCenter().getHearingRoute())
Tests required?

2022-05-30 07:55 UTC, gokul-sol commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceMidEventHandlerTest.java
> -    public void givenAPostponementRequestWithGaps_thenAddAnError() {
@jaberelfasi Why is this test removed please ? Looks valid to me based on the requirement.

2022-05-30 11:10 UTC, johnoneill46 approved these changes

2022-06-06 15:18 UTC, merged