Sscs 10327
hmcts/sscs-tribunals-case-api pull request #2724
Opened 2022-05-29 09:36 UTC by vinothon84

Pull Request for adding hearing Date to excludeDate.

2022-05-29 09:42 UTC, nickwest1 requested changes
Only the one change that's worth applying

2022-05-29 09:42 UTC, nickwest1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandlerTest.java
> +                .arrangements(Arrays.asList("hearingLoop", "signLanguageInterpreter"))
Arrays.asList should be a constant

2022-05-29 10:06 UTC, MohammedHMCTS approved these changes

2022-05-29 10:06 UTC, MohammedHMCTS commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/postponementrequest/PostponementRequestAboutToStartHandlerTest.java
> +        return  hearingOptions;
Just add the return tot he actual builder no point in this if nothing else is happening.

2022-05-29 13:39 UTC, nickwest1 approved these changes

2022-05-30 10:03 UTC, vinothon84 commented
Had a chat with BA team and I need to my code changes to ActionPostponementRequest rather than PostponementRequest so will create a new branch to move my code changes.

2022-05-30 10:03 UTC, closed without merging