SSCS-10538 Post Hearing Request
hmcts/sscs-tribunals-case-api pull request #3060
Opened 2022-11-23 18:09 UTC by TeaWithLucas

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10538

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-25 10:36 UTC, nickhill111 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingSubmittedHandler.java
> +    public boolean canHandle(CallbackType callbackType, Callback<SscsCaseData> callback) {
do these need to be called in the handle method? (several of these in the new files)

2022-11-25 10:36 UTC, nickhill111 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingMidEventHandler.java
> +        switch (typeSelected) {
add space here

2022-11-25 10:52 UTC, amoslv1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingAboutToSubmitHandler.java
> +        log.info("Post Hearing Request: handing action {} for case {}", typeSelected,  caseId);
"handling"?

2022-11-25 10:55 UTC, amoslv1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingSubmittedHandler.java
> +        log.info("Post Hearing Request: handing postHearing {} for case {}", typeSelected,  caseId);
handling

2022-11-25 11:06 UTC, amoslv1 requested changes
Handful of lines without test coverage which you may (or may not) want to address.
https://sonarcloud.io/component_measures?id=SSCSTCA&metric=new_coverage&pullRequest=3060&view=list

Also some superficial typos in log messages.

2022-12-05 12:27 UTC, TeaWithLucas commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingSubmittedHandler.java
> +        log.info("Post Hearing Request: handing postHearing {} for case {}", typeSelected,  caseId);
done

2022-12-05 12:27 UTC, TeaWithLucas commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/requestposthearing/RequestPostHearingAboutToSubmitHandler.java
> +        log.info("Post Hearing Request: handing action {} for case {}", typeSelected,  caseId);
done

2022-12-07 14:04 UTC, nickhill111 approved these changes

2022-12-16 15:07 UTC, nickhill111 approved these changes

2022-12-16 15:44 UTC, amoslv1 approved these changes

2022-12-16 16:17 UTC, amoslv1 approved these changes

2022-12-16 17:12 UTC, nickhill111 approved these changes

2022-12-16 17:12 UTC, merged