SSCS-10112 - Judicial- CCD- Non-standard captialised names are format…
hmcts/sscs-tribunals-case-api pull request #3075
Opened 2022-12-12 12:30 UTC by hajam09

…ted correctly

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-12-19 12:01 UTC, amoslv1 submitted a review, later dismissed

2022-12-20 08:32 UTC, DGordonV1 approved these changes
Approving but minor comment for tests, could we use a static variable for the repeating strings? "*APPELLANT LastNamE" is used multiple times. Not sure if it's worth having this in a utils class elsewhere and pulling it in or declaring at class level for each test class.

2022-12-20 16:49 UTC, StevensonSi submitted a review, later dismissed

2022-12-20 16:53 UTC, EliandroGV1 approved these changes

2022-12-21 08:42 UTC, amoslv1 commented on dependency-check-suppressions.xml
> +    <packageUrl regex="true">^pkg:maven/io\.netty/netty\-buffer@.*$</packageUrl>
All these suppressions can be condensed into a single one with this regex

netty-(\w+-)+4\.1\.85.*$

Since the CVE is fixed in 4.1.86
```suggestion
    <packageUrl regex="true">^pkg:maven/io\.netty/netty-(\w+-)+4\.1\.85.*$</packageUrl>
```

2022-12-21 08:45 UTC, amoslv1 commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/UcWriteFinalDecisionIt.java
> +        assertEquals("AN Test", parentPayload.getAppellantFullName());
Since you've done it for the lastname in other files, would be better to save this AN Test to a constant as well

2022-12-21 08:45 UTC, amoslv1 requested changes
Suggest refining the suppressions, and extracting a string constant for name repetition

2022-12-21 10:22 UTC, amoslv1 commented on dependency-check-suppressions.xml
> +    <packageUrl regex="true">^pkg:maven/io\.netty/netty\-buffer@.*$</packageUrl>
Also this should have an until property. Ideally, the suppressions should be put into a separate PR and whizzed through urgently so that it is not being held up by the rest of this PR.

2022-12-21 11:36 UTC, amoslv1 commented on dependency-check-suppressions.xml
> +  </suppress>
Correction - this suppression should do the job
```suggestion
  <suppress until = "2023-01-08">
    <notes><![CDATA[
   netty 4.1.85
   ]]></notes>
    <packageUrl regex="true">^pkg:maven/io\.netty/netty-\w+@.*$</packageUrl>
    <cve>CVE-2022-41881</cve>
  </suppress>
```

2023-01-10 08:19 UTC, amoslv1 approved these changes

2023-01-18 12:19 UTC, jarekPierchala submitted a review, later dismissed

2023-01-18 13:15 UTC, EliandroGV1 approved these changes

2023-01-30 13:33 UTC, closed without merging