SSCS-11400 - Set Hearing Options For Interpreter Language When Not Selected
hmcts/sscs-tribunals-case-api pull request #3144
Opened 2023-02-10 12:53 UTC by DGordonV1

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-11400

### Change description ###

SSCS-11400 - Set Hearing Options For Interpreter Language When Not Selected

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-13 10:08 UTC, AndreiTrushkov submitted a review, later dismissed

2023-02-13 14:02 UTC, jarekPierchala requested changes

2023-02-13 14:02 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
> +        if (sscsCaseData.getAppeal().getHearingOptions() != null) {
```suggestion
        HearingOptions caseDataHearingOptions = sscsCaseData.getAppeal().getHearingOptions();
hearingOptions = caseDataHearingOptions != null ? caseDataHearingOptions : HearingOptions.builder().build()
```

2023-02-13 16:12 UTC, jarekPierchala submitted a review, later dismissed

2023-02-14 14:01 UTC, AndreiTrushkov approved these changes

2023-02-15 08:58 UTC, amoslv1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
> +            hearingOptions.setLanguages(nonNull(interpreterLanguage.getValue()) ? interpreterLanguage.getValue().getLabel() : NO.getValue());
Need a test for this
![image](https://user-images.githubusercontent.com/110455092/218980938-bbd5a4b1-e6f5-4640-8dcb-d033e1e617ce.png)

2023-02-15 08:59 UTC, amoslv1 requested changes
Add a test case for "No" result

2023-02-17 10:30 UTC, AndreiTrushkov submitted a review, later dismissed

2023-02-17 15:14 UTC, amoslv1 submitted a review, later dismissed

2023-08-14 09:32 UTC, closed without merging

2023-08-14 09:32 UTC, nickhill111 commented
Code moved to SSCS-10865