SSCS-11415 Set up WA preview environment
hmcts/sscs-tribunals-case-api pull request #3156
Opened 2023-02-16 16:41 UTC by markbrooks725

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-11415

### Change description ###
Set up WA preview environment

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-03-20 13:20 UTC, DGordonV1 submitted a review, later dismissed

2023-04-13 13:05 UTC, jarekPierchala requested changes

2023-04-13 13:05 UTC, jarekPierchala commented on charts/sscs-tribunals-api/Chart.yaml
> +version: 0.0.99
possibly outdated, so another bump would be needed

2023-05-01 21:49 UTC, jarekPierchala approved these changes

2024-06-14 08:53 UTC, closed without merging