Sscs 10984 creating new body content for correction
hmcts/sscs-tribunals-case-api pull request #3189
Opened 2023-03-09 16:28 UTC by amoslv1

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10984

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-03-14 09:11 UTC, StevensonSi submitted a review, later dismissed

2023-03-14 11:53 UTC, jarekPierchala submitted a review, later dismissed

2023-04-13 07:48 UTC, DGordonV1 requested changes

2023-04-13 07:48 UTC, DGordonV1 commented on charts/sscs-tribunals-api/values.ccd.preview.template.yaml
> +  enabled: true
Set this back to false, by default for preview envs we don't want to spin up containers unless the dev deploying needs it.

2023-04-13 08:08 UTC, DGordonV1 submitted a review, later dismissed

2023-04-13 09:05 UTC, StevensonSi submitted a review, later dismissed

2023-04-17 07:41 UTC, DGordonV1 approved these changes

2023-04-17 08:15 UTC, merged