SSCS-11601 - force to add other parties during upload response for sscs2 cases
hmcts/sscs-tribunals-case-api pull request #3256
Opened 2023-04-24 11:45 UTC by hajam09

…cs2 cases

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-25 07:19 UTC, DGordonV1 requested changes

2023-04-25 07:19 UTC, DGordonV1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseMidEventHandler.java
> +                && sscsCaseData.getOtherParties() != null && sscsCaseData.getOtherParties().size() == 0) {
```suggestion
                && sscsCaseData.getOtherParties() != null 
                && sscsCaseData.getOtherParties().size() == 0) {
```

2023-04-26 09:26 UTC, DGordonV1 approved these changes

2023-04-26 09:30 UTC, mrmsali approved these changes

2023-05-10 06:47 UTC, merged