SSCS-11703 - Do not send cancellation request to HMC for Issue Decision Notice event
hmcts/sscs-tribunals-case-api pull request #3287
Opened 2023-05-25 12:13 UTC by hajam09

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-05-26 10:26 UTC, nickhill111 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/IssueFinalDecisionAboutToSubmitHandler.java
> +    private boolean anyHearingsScheduledInTheFuture(SscsCaseData caseData) {
might be better to rename to "hasHearingScheduledInTheFuture" or "isHearingScheduledInTheFuture"

2023-05-26 10:26 UTC, nickhill111 approved these changes

2023-05-31 09:11 UTC, DGordonV1 requested changes

2023-05-31 09:11 UTC, DGordonV1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java
> +        Hearing hearing = Hearing.builder().value(HearingDetails.builder()
```suggestion
        HearingDetails details = HearingDetails.builder()...
        Hearing hearing = Hearing.builder().value(details)
```
Basically, separate out any nested builders, easier to read. Could extend to other test classes you've updated too.

2023-05-31 09:11 UTC, DGordonV1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issuefinaldecision/esa/EsaIssueFinalDecisionAboutToSubmitHandlerTest.java
> +        DocumentLink docLink = DocumentLink.builder().documentUrl("bla.com").documentFilename(String.format("Decision Notice issued on %s.pdf", LocalDate.now().format(DateTimeFormatter.ofPattern("dd-
Could probably block this out to separate lines for each param. Same across other files too.

2023-05-31 11:10 UTC, DGordonV1 submitted a review, later dismissed

2023-05-31 11:30 UTC, DGordonV1 approved these changes

2023-06-27 09:56 UTC, merged