SSCS-11706 - Error when attempting to upload hearing recording onto a List assist case
hmcts/sscs-tribunals-case-api pull request #3299
Opened 2023-06-01 08:36 UTC by hajam09

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-06-01 12:44 UTC, jarekPierchala requested changes

2023-06-01 13:13 UTC, amoslv1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandlerTest.java
> +        selectHearingDetails.forEach(o -> assertEquals("venue name 09:00:00 06 Jun 2021", o.getLabel()));
You can avoid using a forEach
```suggestion
        assertTrue(selectHearingDetails.stream()
    .allMatch(o -> "venue name 09:00:00 06 Jun 2021".equals(o.getLabel())));
```

2023-06-01 13:14 UTC, amoslv1 requested changes
small optimisation in test

2023-06-07 08:51 UTC, EliandroGV1 submitted a review, later dismissed

2023-06-09 08:02 UTC, amoslv1 submitted a review, later dismissed

2023-06-09 08:14 UTC, jarekPierchala approved these changes

2023-07-19 11:48 UTC, nickhill111 approved these changes

2023-07-25 09:02 UTC, EliandroGV1 approved these changes

2023-08-07 11:11 UTC, jarekPierchala requested changes

2023-08-07 11:11 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java
> +        return returnValue + " " + hearingDate;
```suggestion
      
        return !hearingTime.equals("") ? returnValue + " " + hearingTime : returnValue + " " + hearingDate;
```

2023-08-07 11:18 UTC, AndreiTrushkov approved these changes

2023-08-07 11:22 UTC, hajam09 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/uploadhearingrecording/UploadHearingRecordingAboutToStartHandler.java
> +        return returnValue + " " + hearingDate;
Unfortunately, this is breaks my test.

2023-08-07 11:24 UTC, jarekPierchala approved these changes

2023-08-07 11:24 UTC, merged