SSCS-11743-Action-postponment-update-case-state
hmcts/sscs-tribunals-case-api pull request #3304
Opened 2023-06-16 15:21 UTC by StevensonSi

**Before creating a pull request make sure that:**

- [ x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

[### JIRA link (if applicable) ###
](https://tools.hmcts.net/jira/browse/SSCS-11743)

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-06-19 16:23 UTC, nickhill111 requested changes

2023-06-19 16:23 UTC, nickhill111 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandler.java
> +            sscsCaseData.setState(State.NOT_LISTABLE);
you can simplify this with:
sscsCaseData.setState(State.valueOf(listingOption));
Doing this should also sort out your Code coverage (check sonarcube)

2023-06-20 07:12 UTC, amoslv1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java
> +        sscsCaseData.getPostponementRequest().setListingOption("readyToList");
Please save "readyToList" as a constant, or use State.READY_TO_LIST.getType(), and replace all usages in the test class

2023-06-20 07:13 UTC, amoslv1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/actionpostponementrequest/ActionPostponementRequestAboutToSubmitHandlerTest.java
> +        sscsCaseData.getPostponementRequest().setListingOption("notListable");
Can do same here, constant or getType

2023-06-20 07:13 UTC, amoslv1 requested changes
replace string literals in the test

2023-06-20 12:42 UTC, nickhill111 submitted a review, later dismissed

2023-06-20 13:06 UTC, amoslv1 approved these changes

2023-07-10 10:33 UTC, jarekPierchala approved these changes

2023-07-10 12:35 UTC, nickhill111 approved these changes

2023-07-10 13:14 UTC, merged