SSCS-11709 - Add error for unavailable dates on update to case data and update other party data
hmcts/sscs-tribunals-case-api pull request #3335
Opened 2023-07-04 09:11 UTC by hajam09

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-07 14:21 UTC, nickhill111 requested changes

2023-07-07 14:21 UTC, nickhill111 commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsHelper.java
> +            // when the user select yes to unavailable dates, but does not add an entry.
remove comment

2023-07-07 14:21 UTC, nickhill111 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
> +        assertThat(response.getErrors().isEmpty(), is(true));
missing a few bits of CC:
https://sonarcloud.io/summary/new_code?id=SSCSTCA&pullRequest=3335

2023-07-07 15:25 UTC, nickhill111 approved these changes

2023-07-10 08:28 UTC, StevensonSi approved these changes

2023-07-10 10:39 UTC, jarekPierchala requested changes

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
> +        callback.getCaseDetails().getCaseData().getAppeal().setHearingOptions(HearingOptions.builder().wantsToAttend("Yes").scheduleHearing("Yes").build());
callback.getCaseDetails().getCaseData().getAppeal() to sepatate var

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
> +        callback.getCaseDetails().getCaseData().getAppeal().setHearingOptions(HearingOptions.builder().wantsToAttend("Yes").scheduleHearing("Yes").build());
callback.getCaseDetails().getCaseData().getAppeal() to sepatate var

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
> +        callback.getCaseDetails().getCaseData().getAppeal().setHearingOptions(HearingOptions.builder().wantsToAttend("Yes").scheduleHearing("Yes").build());
same

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
> +        callback.getCaseDetails().getCaseData().getAppeal().setHearingOptions(HearingOptions.builder().wantsToAttend("Yes").scheduleHearing("Yes").build());
same

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandlerTest.java
> +            .benefitType(BenefitType.builder().code(Benefit.CHILD_SUPPORT.getShortName()).build())
BenefitType.builder().code(Benefit.CHILD_SUPPORT.getShortName()).build() as separate var

2023-07-10 10:39 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updateotherparty/UpdateOtherPartyAboutToSubmitHandlerTest.java
> +            .benefitType(BenefitType.builder().code(Benefit.CHILD_SUPPORT.getShortName()).build())
Check for simillar stuff below

2023-07-10 12:00 UTC, AndreiTrushkov submitted a review, later dismissed

2023-07-10 15:58 UTC, jarekPierchala submitted a review, later dismissed

2023-07-11 08:15 UTC, mrmsali submitted a review, later dismissed

2023-07-11 08:16 UTC, StevensonSi approved these changes

2023-07-11 08:38 UTC, nickhill111 submitted a review, later dismissed

2023-08-09 11:44 UTC, nickhill111 submitted a review, later dismissed

2023-08-09 12:09 UTC, StevensonSi approved these changes

2023-08-10 09:41 UTC, StevensonSi approved these changes

2023-08-10 09:44 UTC, mrmsali approved these changes

2023-08-10 09:48 UTC, merged