Sscs 11623 fee paid judge
hmcts/sscs-tribunals-case-api pull request #3371
Opened 2023-07-21 15:22 UTC by nickhill111

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-25 13:21 UTC, AndreiTrushkov submitted a review, later dismissed

2023-09-13 14:15 UTC, jarekPierchala approved these changes

2023-09-14 08:13 UTC, DGordonV1 requested changes

2023-09-14 08:13 UTC, DGordonV1 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandlerTest.java
> +        handler = new WriteFinalDecisionAboutToStartHandler(userDetailsService,  true);
double spacing on params, remove extra space.

2023-09-14 08:15 UTC, nickhill111 commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/writefinaldecision/WriteFinalDecisionAboutToStartHandlerTest.java
> +        handler = new WriteFinalDecisionAboutToStartHandler(userDetailsService,  true);
done

2023-09-14 08:15 UTC, nickhill111 commented on src/main/resources/config/application.properties
> +
done

2023-09-14 08:15 UTC, DGordonV1 approved these changes

2023-09-14 08:16 UTC, AndreiTrushkov approved these changes

2023-09-14 08:49 UTC, merged