SSCSCI-830 - Dwp Response Date Notifications
hmcts/sscs-tribunals-case-api pull request #3784
Opened 2024-04-29 13:43 UTC by gemmatalbot

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCSCI-830

### Change description ###
MYA status tab should show the dwp due date as:

Child Support cases should be calculated as 'Sent to FTA' event's date plus 42 days
All other case types as plus 28 days

2024-04-30 11:09 UTC, sanjayparekh-hmcts requested changes

2024-04-30 11:09 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java
> +    public static int calculateMaxDwpResponseDays(String benefitCode) {
There really should not be any static methods on a component

2024-05-01 08:29 UTC, sanjayparekh-hmcts requested changes

2024-05-01 08:29 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java
> +        if (dateSentToDwp != null && isNotBlank(dateSentToDwp)) {
isNotBlank already checks for null

2024-05-01 08:29 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/sscs/builder/TrackYourAppealJsonBuilder.java
> +                if (dateSentToDwp != null && isNotBlank(dateSentToDwp)) {
same

2024-05-02 09:56 UTC, sanjayparekh-hmcts submitted a review, later dismissed

2024-05-02 10:48 UTC, KatKovacs1 approved these changes

2024-05-02 15:40 UTC, benouaer approved these changes

2024-06-25 09:10 UTC, nitinprabhuhmcts submitted a review, later dismissed

2024-06-25 09:14 UTC, hashimalisolirius submitted a review, later dismissed

2024-06-25 09:38 UTC, nitinprabhuhmcts approved these changes

2024-06-25 09:38 UTC, hashimalisolirius approved these changes

2024-06-25 09:57 UTC, merged