new field sorInTime and logic to process it
hmcts/sscs-tribunals-case-api pull request #3798
Opened 2024-05-07 10:14 UTC by AndreiTrushkov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCS-12334

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-15 07:50 UTC, DGordonV1 requested changes

2024-05-15 07:50 UTC, DGordonV1 commented on src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java
> +        LocalDate decisionDate = LocalDate.parse(decisionDateAdded);
Could this be moved just before implementation? It's not being used in the next if statement.

2024-05-15 07:50 UTC, DGordonV1 commented on src/main/java/uk/gov/hmcts/reform/sscs/util/SscsUtil.java
> +        if (diff <= 31) {
We could refactor the magic number here.

2024-05-15 08:26 UTC, DGordonV1 approved these changes

2024-06-17 09:57 UTC, markbrooks725 approved these changes

2024-06-17 13:27 UTC, DGordonV1 submitted a review, later dismissed

2024-10-08 12:01 UTC, closed without merging