SSCSSI-337: Fix broken trigger for CcdCallbackMapService - Post Heari…
hmcts/sscs-tribunals-case-api pull request #3882
Opened 2024-07-08 13:46 UTC by srochani

…ng Review Event

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-07-17 14:56 UTC, sanjayparekh-hmcts requested changes

2024-07-17 14:56 UTC, sanjayparekh-hmcts commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/posthearingreview/PostHearingReviewSubmittedHandlerTest.java
> +    void givenActionTypeSetAsideSelectedIsNotRefuse_shouldNotUpdateCaseWIthCcdService_whenCcdCallbackMapV2IsEnabled(SetAsideActions action) {
is there any benefit to having this a ParameterizedTest if there is only one enum value?

2024-07-17 14:56 UTC, sanjayparekh-hmcts commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/posthearingreview/PostHearingReviewSubmittedHandlerTest.java
> +    @EnumSource(value = YesNo.class, names = {"NO"})
same Q here

2024-08-14 13:50 UTC, SomeshRA approved these changes
LGTM

2024-10-28 10:14 UTC, sanjayparekh-hmcts approved these changes

2024-10-28 13:29 UTC, SomeshRA approved these changes
LGTM

2024-10-28 13:46 UTC, merged