Initial hearing-api merge
hmcts/sscs-tribunals-case-api pull request #3930
Opened 2024-08-09 13:16 UTC by srochani

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-10-02 08:31 UTC, sanjayparekh-hmcts submitted a review, later dismissed

2024-10-02 08:48 UTC, adusumillipraveen submitted a review, later dismissed

2024-10-03 08:48 UTC, srochani commented
closing and reopening

2024-10-04 12:56 UTC, srochani commented
closing the PR

2024-10-10 08:12 UTC, SomeshRA approved these changes

2024-10-10 08:26 UTC, sanjayparekh-hmcts requested changes

2024-10-10 08:26 UTC, sanjayparekh-hmcts commented on Jenkinsfile_CNP
> -    'sscs-${env}': [
All these look like just a whitespace change - can you confirm and if not needed, revert to master please

2024-10-10 10:34 UTC, srochani commented
closing and opening new PR

2024-10-10 10:34 UTC, closed without merging