SSCSSI-371: SSCS common changes and added functional test
hmcts/sscs-tribunals-case-api pull request #3937
Opened 2024-08-19 18:57 UTC by SomeshRA

### Jira link
https://tools.hmcts.net/jira/browse/SSCSSI-371

### Change description

SSCS common changes and added functional test

### Testing done

### Checklist

- [X ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-08-21 12:29 UTC, sanjayparekh-hmcts requested changes

2024-08-21 12:29 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/sendtofirsttier/SendToFirstTierSubmittedHandlerTest.java
> +        assertThat(result.getDwpState()).as(result.getCcdCaseId())
can you remove the result stuff please?

2024-08-23 10:57 UTC, SomeshRA commented on src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/sendtofirsttier/SendToFirstTierSubmittedHandlerTest.java
> +        assertThat(result.getDwpState()).as(result.getCcdCaseId())
removed result

2024-08-23 11:29 UTC, srochani approved these changes

2024-08-23 12:21 UTC, sanjayparekh-hmcts approved these changes

2024-09-02 12:12 UTC, srochani approved these changes

2024-09-02 12:21 UTC, sanjayparekh-hmcts approved these changes

2024-09-02 12:21 UTC, merged