After SSCSSI-404 release cleanup
hmcts/sscs-tribunals-case-api pull request #4074
Opened 2024-10-21 14:24 UTC by srochani

### Jira link

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

### Change description

### Testing done

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-10-21 15:18 UTC, sanjayparekh-hmcts requested changes

2024-10-21 16:58 UTC, SomeshRA requested changes
I suppose we need to clean up from these charts as well
https://github.com/hmcts/sscs-tribunals-case-api/blob/clean-up-hearing-preview/charts/sscs-tribunals-api/Chart.yaml#L51
https://github.com/hmcts/sscs-tribunals-case-api/blob/clean-up-hearing-preview/charts/sscs-tribunals-api/values.yaml#L179

2024-10-22 14:48 UTC, sanjayparekh-hmcts approved these changes

2024-10-22 14:48 UTC, sanjayparekh-hmcts commented on Jenkinsfile_CNP
> +        echo "isHearingsPr  " + isHearingsPr
need this?

2024-10-22 14:50 UTC, srochani commented on Jenkinsfile_CNP
> +        echo "isHearingsPr  " + isHearingsPr
needed for debug :-)

2024-10-22 14:51 UTC, srochani commented on src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java
> -        log.info("isByPassHearingServiceEnabled && isDeploymentFilterEnabled ------------------------> {}, {}", isByPassHearingServiceEnabled,
updated to keep this log.info

2024-10-22 14:51 UTC, srochani commented on src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/TribunalsHearingsEventQueueListener.java
> -        log.info("isByPassHearingServiceEnabled ------------------------> {}", isByPassHearingServiceEnabled);
updated to keep this log.info

2024-10-22 14:52 UTC, gokul-sol approved these changes

2024-10-22 14:53 UTC, merged