SSCSSI-95: C1b: updateCaseOnly - ReIssueFurtherEvidenceHandler
hmcts/sscs-tribunals-case-api pull request #4118
Opened 2024-11-07 13:20 UTC by srochani

### Jira link

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

### Change description

### Testing done

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-11-08 09:42 UTC, SomeshRA commented on src/main/java/uk/gov/hmcts/reform/sscs/evidenceshare/callback/handlers/ReissueFurtherEvidenceHandler.java
> +                    setReissueFlagsToNull(caseData);
CaseData should be retrieved from SccsCaseDetails which is passed in

2024-11-08 10:20 UTC, sanjayparekh-hmcts requested changes

2024-11-08 12:02 UTC, sanjayparekh-hmcts approved these changes

2024-11-08 12:34 UTC, SomeshRA approved these changes
LGTM

2024-11-13 14:47 UTC, srochani commented
closing and reopening the PR

2024-11-13 16:47 UTC, sanjayparekh-hmcts approved these changes

2024-11-13 16:54 UTC, SomeshRA approved these changes

2024-11-14 09:34 UTC, merged